name: objai
description: A new Flutter project for Objai.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.3.0
  dio: ^5.3.0
  image_picker: ^0.8.7+4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  intl: ^0.18.0
  uuid: ^3.0.7
  url_launcher: ^6.1.10
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true